apiVersion: v1
kind: Service
metadata:
  name: deploygate-service
spec:
  type: NodePort
  selector:
    app: deploygate
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
      nodePort: {{ .Values.app.nodePort }}
